# Code Generated by Sidekick is for learning and experimentation purposes only.
# core/__init__.py
"""
Core modules for trivia transcription

This package contains the main functionality for:
- Live stream audio capture from Twitch
- Real-time speech-to-text transcription
- Intelligent question extraction using LLM
- Excel file management and output
- Sliding window audio processing pipeline
"""

from .live_stream_capture import LiveTwitchAudioCapture
from .streaming_transcription import StreamingTranscriber
from .question_extractor import QuestionExtractor
from .excel_manager import TriviaExcelManager
from .sliding_window_processor import SlidingWindowProcessor

__version__ = '1.0.0'

__all__ = [
    'LiveTwitchAudioCapture',
    'StreamingTranscriber',
    'QuestionExtractor',
    'TriviaExcelManager',
    'SlidingWindowProcessor'
]
