# Code Generated by Sidekick is for learning and experimentation purposes only.
# excel_manager.py
import pandas as pd
from openpyxl import load_workbook, Workbook
from openpyxl.styles import Font, PatternFill, Alignment
import os
from datetime import datetime

class TriviaExcelManager:
    def __init__(self, filename="trivia_questions.xlsx"):
        self.filename = filename
        self.initialize_workbook()
        
    def initialize_workbook(self):
        """Create workbook if it doesn't exist"""
        if not os.path.exists(self.filename):
            wb = Workbook()
            wb.remove(wb.active)  # Remove default sheet
            wb.save(self.filename)
    
    def ensure_sheet_exists(self, hour_number: int):
        """Create sheet for specific hour if it doesn't exist"""
        wb = load_workbook(self.filename)
        sheet_name = f"Hour {hour_number}"
        
        if sheet_name not in wb.sheetnames:
            ws = wb.create_sheet(sheet_name)
            
            # Create headers
            headers = ["Question #", "Question Text", "Song Played", "Timestamp", "Picture Q?"]
            ws.append(headers)
            
            # Style headers
            for cell in ws[1]:
                cell.font = Font(bold=True, size=12)
                cell.fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
                cell.font = Font(bold=True, color="FFFFFF")
                cell.alignment = Alignment(horizontal="center")
            
            # Set column widths
            ws.column_dimensions['A'].width = 12
            ws.column_dimensions['B'].width = 80
            ws.column_dimensions['C'].width = 40
            ws.column_dimensions['D'].width = 20
            ws.column_dimensions['E'].width = 12
            
            wb.save(self.filename)
    
    def add_question(self, hour_number: int, question_number: int, 
                     question_text: str, song: str = "", 
                     is_picture_question: bool = False):
        """Add a new question to the appropriate sheet"""
        self.ensure_sheet_exists(hour_number)
        
        wb = load_workbook(self.filename)
        ws = wb[f"Hour {hour_number}"]
        
        timestamp = datetime.now().strftime("%H:%M:%S")
        picture_marker = "YES" if is_picture_question else ""
        
        # Append new row
        ws.append([
            question_number,
            question_text,
            song,
            timestamp,
            picture_marker
        ])
        
        # Enable text wrapping for question column
        last_row = ws.max_row
        ws.cell(row=last_row, column=2).alignment = Alignment(wrap_text=True, vertical="top")
        
        wb.save(self.filename)
        print(f"✓ Added to Excel: Hour {hour_number}, Question {question_number}")
    
    def get_recent_questions(self, hour_number: int, limit: int = 5) -> list:
        """Get recent questions from a specific hour for deduplication"""
        if not os.path.exists(self.filename):
            return []
        
        wb = load_workbook(self.filename)
        sheet_name = f"Hour {hour_number}"
        
        if sheet_name not in wb.sheetnames:
            return []
        
        ws = wb[sheet_name]
        questions = []
        
        # Get last N questions (column B, skipping header)
        for row in range(max(2, ws.max_row - limit + 1), ws.max_row + 1):
            cell_value = ws.cell(row=row, column=2).value
            if cell_value:
                questions.append(cell_value)
        
        return questions
