# Code Generated by Sidekick is for learning and experimentation purposes only.
# live_stream_capture.py
import streamlink
import subprocess
import threading
import queue
import numpy as np
import wave
import io

class LiveTwitchAudioCapture:
    def __init__(self, twitch_channel_url, sample_rate=16000):
        """
        twitch_channel_url: e.g., "https://www.twitch.tv/channelname"
        sample_rate: 16kHz is optimal for Whisper
        """
        self.channel_url = twitch_channel_url
        self.sample_rate = sample_rate
        self.is_streaming = False
        self.audio_queue = queue.Queue(maxsize=100)  # Prevent memory overflow
        self.ffmpeg_process = None
        
    def start_stream(self):
        """Start capturing live audio from Twitch"""
        print(f"🔴 Connecting to Twitch stream: {self.channel_url}")
        
        # Get stream URL using streamlink
        try:
            streams = streamlink.streams(self.channel_url)
            
            # Try to get audio-only stream first (lowest bandwidth)
            if "audio_only" in streams:
                stream = streams["audio_only"]
                print("✓ Using audio-only stream")
            elif "160p" in streams:  # Lowest video quality as fallback
                stream = streams["160p"]
                print("✓ Using 160p stream (extracting audio)")
            elif "worst" in streams:
                stream = streams["worst"]
                print("✓ Using worst quality stream (extracting audio)")
            else:
                raise Exception("No suitable stream quality found")
            
            stream_url = stream.url
            
        except Exception as e:
            raise Exception(f"Failed to connect to Twitch: {e}")
        
        # FFmpeg command to extract audio in real-time
        ffmpeg_cmd = [
            'ffmpeg',
            '-i', stream_url,
            '-f', 's16le',           # Raw PCM audio
            '-acodec', 'pcm_s16le',  # 16-bit PCM
            '-ar', str(self.sample_rate),  # Resample to 16kHz
            '-ac', '1',              # Mono audio
            '-loglevel', 'error',    # Suppress ffmpeg output
            'pipe:1'                 # Output to stdout
        ]
        
        # Start FFmpeg process
        self.ffmpeg_process = subprocess.Popen(
            ffmpeg_cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            bufsize=10**8  # Large buffer
        )
        
        self.is_streaming = True
        print("✓ Live stream connected!")
        
        # Start thread to read audio data
        self.capture_thread = threading.Thread(target=self._capture_audio_loop, daemon=True)
        self.capture_thread.start()
    
    def _capture_audio_loop(self):
        """Continuously read audio data from FFmpeg and put into queue"""
        chunk_size = self.sample_rate * 2  # 2 bytes per sample (int16)
        
        while self.is_streaming and self.ffmpeg_process:
            try:
                # Read audio chunk (1 second of audio)
                audio_data = self.ffmpeg_process.stdout.read(chunk_size)
                
                if not audio_data:
                    print("⚠️  Stream ended or connection lost")
                    break
                
                # Convert bytes to numpy array
                audio_array = np.frombuffer(audio_data, dtype=np.int16)
                
                # Add to queue (non-blocking to prevent deadlock)
                try:
                    self.audio_queue.put(audio_array, block=False)
                except queue.Full:
                    # If queue is full, skip this chunk (acceptable for live stream)
                    pass
                    
            except Exception as e:
                print(f"Error reading stream: {e}")
                break
    
    def get_audio_buffer(self, duration_seconds=30):
        """
        Get accumulated audio buffer of specified duration
        Returns numpy array of audio samples
        """
        target_samples = self.sample_rate * duration_seconds
        accumulated_audio = []
        
        # Collect audio from queue until we have enough
        while sum(len(chunk) for chunk in accumulated_audio) < target_samples:
            try:
                chunk = self.audio_queue.get(timeout=1.0)
                accumulated_audio.append(chunk)
            except queue.Empty:
                # If queue is empty, return what we have
                break
        
        if not accumulated_audio:
            return None
        
        # Concatenate all chunks
        audio_buffer = np.concatenate(accumulated_audio)
        
        # Trim to exact duration
        if len(audio_buffer) > target_samples:
            audio_buffer = audio_buffer[:target_samples]
        
        return audio_buffer
    
    def save_buffer_to_wav(self, audio_buffer, filename):
        """Save numpy audio buffer to WAV file"""
        with wave.open(filename, 'wb') as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)  # 16-bit = 2 bytes
            wf.setframerate(self.sample_rate)
            wf.writeframes(audio_buffer.tobytes())
    
    def stop_stream(self):
        """Stop capturing stream"""
        self.is_streaming = False
        
        if self.ffmpeg_process:
            self.ffmpeg_process.terminate()
            self.ffmpeg_process.wait(timeout=5)
            self.ffmpeg_process = None
        
        print("⏹️  Stream capture stopped")
    
    def __del__(self):
        """Cleanup on destruction"""
        self.stop_stream()
