# Code Generated by Sidekick is for learning and experimentation purposes only.
# live_trivia_assistant.py
import os
import time
from collections.abc import Callable
from typing import Optional

from config import Config
from .ExcelManager import TriviaExcelManager
from .LiveTwitchAudioCatcher import LiveTwitchAudioCapture
from .QuestionExtractor import QuestionExtractor
from .SlidingWindowProcessor import SlidingWindowProcessor
from .StreamingTranscriber import StreamingTranscriber


class LiveTriviaAssistant:
    def __init__(
        self,
        twitch_channel_url: str,
        on_transcription: Optional[Callable[[str], None]] = None,
        quiet: bool = False,
    ):
        """Wire capture, transcription, extraction, and sliding-window processing.

        Args:
            twitch_channel_url: Full Twitch channel URL (e.g. https://www.twitch.tv/name).
            on_transcription: Optional callback for each non-duplicate transcription.
            quiet: If True, omit decorative console output (e.g. for API use).
        """
        self._quiet = quiet
        if not quiet:
            print("=" * 60)
            print("🎮 LIVE TRIVIA ASSISTANT")
            print("=" * 60)

        self.stream_capture = LiveTwitchAudioCapture(twitch_channel_url)
        self.transcriber = StreamingTranscriber(
            model_size=Config.WHISPER_MODEL_SIZE,
            device=Config.WHISPER_DEVICE,
        )

        if Config.ENABLE_QUESTION_EXTRACTION:
            self.extractor = QuestionExtractor(api_key=os.getenv("OPENAI_API_KEY"))
            self.excel_manager = TriviaExcelManager()
        else:
            self.extractor = None
            self.excel_manager = None

        self.processor = SlidingWindowProcessor(
            stream_capture=self.stream_capture,
            transcriber=self.transcriber,
            extractor=self.extractor,
            excel_manager=self.excel_manager,
            audio_window_seconds=Config.AUDIO_WINDOW_SECONDS,
            segment_interval_seconds=Config.SEGMENT_INTERVAL_SECONDS,
            on_transcription=on_transcription,
            enable_question_extraction=Config.ENABLE_QUESTION_EXTRACTION,
        )

        self.is_running = False

    def start(self):
        """Start capturing and processing the live stream.

        Raises:
            Exception: Propagates connection or pipeline errors from capture or processing.
        """
        try:
            self.stream_capture.start_stream()

            if not self._quiet:
                print("⏳ Waiting for stream to stabilize...")
            time.sleep(3)

            self.processor.start_processing()

            self.is_running = True
            if not self._quiet:
                print("\n✅ LIVE PROCESSING ACTIVE")
                print("=" * 60)

        except Exception as e:
            if not self._quiet:
                print(f"❌ Failed to start: {e}")
            raise

    def stop(self):
        """Stop processing and release the stream."""
        if not self._quiet:
            print("\n🛑 Stopping...")
        self.processor.stop_processing()
        self.stream_capture.stop_stream()
        self.is_running = False
        if not self._quiet:
            print("✓ Stopped")
    
    def run_interactive(self):
        """Run the assistant until the user stops via CLI commands or Ctrl+C."""
        self.start()
        
        print("\nCommands:")
        print("  'h [number]' - Set hour number (e.g., 'h 2')")
        print("  'status' - Show current status")
        print("  'stop' - Stop and exit")
        print("\n" + "=" * 60)
        
        try:
            while self.is_running:
                cmd = input("\n> ").strip().lower()
                
                if cmd.startswith('h '):
                    try:
                        hour_num = int(cmd.split()[1])
                        self.processor.set_hour(hour_num)
                    except (ValueError, IndexError):
                        print("⚠️  Invalid format. Use: h [number]")
                
                elif cmd == 'status':
                    print(f"📊 Current Hour: {self.processor.current_hour}")
                    print(f"📊 Questions Captured: {self.processor.question_count}")
                    print(f"📊 Stream Active: {self.stream_capture.is_streaming}")
                
                elif cmd == 'stop':
                    break
                
                else:
                    print("⚠️  Unknown command")
        
        except KeyboardInterrupt:
            print("\n")
        
        finally:
            self.stop()
            print("👋 Goodbye!")

if __name__ == "__main__":
    # Example usage
    TWITCH_CHANNEL = "https://m.twitch.tv/neglagonave"
    
    assistant = LiveTriviaAssistant(TWITCH_CHANNEL)
    assistant.run_interactive()
