# Code Generated by Sidekick is for learning and experimentation purposes only.
# live_trivia_assistant.py
import os
import time
from dotenv import load_dotenv
from .LiveTwitchAudioCatcher import LiveTwitchAudioCapture
from .StreamingTranscriber import StreamingTranscriber
from .QuestionExtractor import QuestionExtractor
from .ExcelManager import TriviaExcelManager
from .SlidingWindowProcessor import SlidingWindowProcessor

class LiveTriviaAssistant:
    def __init__(self, twitch_channel_url):
        load_dotenv()
        
        print("=" * 60)
        print("🎮 LIVE TRIVIA ASSISTANT")
        print("=" * 60)
        
        # Initialize components
        self.stream_capture = LiveTwitchAudioCapture(twitch_channel_url)
        self.transcriber = StreamingTranscriber(model_size="base", device="cpu")
        self.extractor = QuestionExtractor(api_key=os.getenv("OPENAI_API_KEY"))
        self.excel_manager = TriviaExcelManager()
        
        self.processor = SlidingWindowProcessor(
            stream_capture=self.stream_capture,
            transcriber=self.transcriber,
            extractor=self.extractor,
            excel_manager=self.excel_manager,
            window_duration=30,    # Process 30 seconds at a time
            overlap_duration=15    # 50% overlap to catch full questions
        )
        
        self.is_running = False
    
    def start(self):
        """Start capturing and processing live stream"""
        try:
            # Connect to Twitch stream
            self.stream_capture.start_stream()
            
            # Give stream a moment to stabilize
            print("⏳ Waiting for stream to stabilize...")
            time.sleep(3)
            
            # Start processing
            self.processor.start_processing()
            
            self.is_running = True
            print("\n✅ LIVE PROCESSING ACTIVE")
            print("=" * 60)
            
        except Exception as e:
            print(f"❌ Failed to start: {e}")
            raise
    
    def stop(self):
        """Stop everything"""
        print("\n🛑 Stopping...")
        self.processor.stop_processing()
        self.stream_capture.stop_stream()
        self.is_running = False
        print("✓ Stopped")
    
    def run_interactive(self):
        """Run with interactive CLI"""
        self.start()
        
        print("\nCommands:")
        print("  'h [number]' - Set hour number (e.g., 'h 2')")
        print("  'status' - Show current status")
        print("  'stop' - Stop and exit")
        print("\n" + "=" * 60)
        
        try:
            while self.is_running:
                cmd = input("\n> ").strip().lower()
                
                if cmd.startswith('h '):
                    try:
                        hour_num = int(cmd.split()[1])
                        self.processor.set_hour(hour_num)
                    except (ValueError, IndexError):
                        print("⚠️  Invalid format. Use: h [number]")
                
                elif cmd == 'status':
                    print(f"📊 Current Hour: {self.processor.current_hour}")
                    print(f"📊 Questions Captured: {self.processor.question_count}")
                    print(f"📊 Stream Active: {self.stream_capture.is_streaming}")
                
                elif cmd == 'stop':
                    break
                
                else:
                    print("⚠️  Unknown command")
        
        except KeyboardInterrupt:
            print("\n")
        
        finally:
            self.stop()
            print("👋 Goodbye!")

if __name__ == "__main__":
    # Example usage
    TWITCH_CHANNEL = "https://www.twitch.tv/YOUR_CHANNEL_NAME"
    
    assistant = LiveTriviaAssistant(TWITCH_CHANNEL)
    assistant.run_interactive()
