# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Live audio capture: Twitch via Streamlink, or any HTTP(S) stream URL via FFmpeg."""
from __future__ import annotations

import queue
import subprocess
import threading
from urllib.parse import urlparse

import numpy as np
import wave
from streamlink.session import Streamlink

from utils.ssl_verify import resolve_streamlink_ssl_verify


def _is_twitch_url(url: str) -> bool:
    """Return True if the URL points at twitch.tv (Streamlink path)."""

    host = (urlparse(url).hostname or "").lower()
    return "twitch.tv" in host


class LiveStreamAudioCapture:
    """Capture live audio from Twitch (Streamlink) or a direct HTTP(S) stream (FFmpeg)."""

    def __init__(self, stream_url: str, sample_rate: int = 16000) -> None:
        """
        Args:
            stream_url: Twitch channel URL, or a direct stream URL (e.g. Icecast ``.mp3``).
            sample_rate: Target sample rate (16 kHz is optimal for Whisper).
        """
        self.stream_url = stream_url.strip()
        self.sample_rate = sample_rate
        self.is_streaming = False
        self.audio_queue: queue.Queue = queue.Queue(maxsize=100)
        self.ffmpeg_process: subprocess.Popen | None = None

    def start_stream(self) -> None:
        """Start capturing live audio and feeding the internal queue."""

        if _is_twitch_url(self.stream_url):
            print(f"🔴 Connecting to Twitch stream: {self.stream_url}")
            ffmpeg_input_url = self._resolve_twitch_ffmpeg_input()
        else:
            print(f"🔴 Connecting to HTTP stream: {self.stream_url}")
            ffmpeg_input_url = self.stream_url

        ffmpeg_cmd: list[str] = ["ffmpeg"]
        if not _is_twitch_url(self.stream_url):
            ffmpeg_cmd += [
                "-reconnect",
                "1",
                "-reconnect_streamed",
                "1",
                "-reconnect_delay_max",
                "4",
            ]
        ffmpeg_cmd += [
            "-i",
            ffmpeg_input_url,
            "-f",
            "s16le",
            "-acodec",
            "pcm_s16le",
            "-ar",
            str(self.sample_rate),
            "-ac",
            "1",
            "-loglevel",
            "error",
            "pipe:1",
        ]

        self.ffmpeg_process = subprocess.Popen(
            ffmpeg_cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            bufsize=10**8,
        )

        self.is_streaming = True
        print("✓ Live stream connected!")

        self.capture_thread = threading.Thread(target=self._capture_audio_loop, daemon=True)
        self.capture_thread.start()

    def _resolve_twitch_ffmpeg_input(self) -> str:
        """Use Streamlink to resolve a playable URL for FFmpeg."""

        try:
            session = Streamlink()
            session.set_option("http-ssl-verify", resolve_streamlink_ssl_verify())
            streams = session.streams(self.stream_url)

            if "audio_only" in streams:
                stream = streams["audio_only"]
                print("✓ Using audio-only stream")
            elif "160p" in streams:
                stream = streams["160p"]
                print("✓ Using 160p stream (extracting audio)")
            elif "worst" in streams:
                stream = streams["worst"]
                print("✓ Using worst quality stream (extracting audio)")
            else:
                raise RuntimeError("No suitable stream quality found")

            return stream.url

        except Exception as e:
            raise RuntimeError(f"Failed to connect to Twitch: {e}") from e

    def _capture_audio_loop(self) -> None:
        """Continuously read PCM from FFmpeg and enqueue int16 chunks."""

        chunk_size = self.sample_rate * 2

        while self.is_streaming and self.ffmpeg_process:
            try:
                assert self.ffmpeg_process.stdout is not None
                audio_data = self.ffmpeg_process.stdout.read(chunk_size)

                if not audio_data:
                    print("⚠️  Stream ended or connection lost")
                    break

                audio_array = np.frombuffer(audio_data, dtype=np.int16)

                try:
                    self.audio_queue.put(audio_array, block=False)
                except queue.Full:
                    pass

            except Exception as e:
                print(f"Error reading stream: {e}")
                break

    def get_audio_buffer(self, duration_seconds: int = 30):
        """Return accumulated audio as int16 numpy array, or None if no data."""

        target_samples = self.sample_rate * duration_seconds
        accumulated_audio: list[np.ndarray] = []

        while sum(len(chunk) for chunk in accumulated_audio) < target_samples:
            try:
                chunk = self.audio_queue.get(timeout=1.0)
                accumulated_audio.append(chunk)
            except queue.Empty:
                break

        if not accumulated_audio:
            return None

        audio_buffer = np.concatenate(accumulated_audio)

        if len(audio_buffer) > target_samples:
            audio_buffer = audio_buffer[:target_samples]

        return audio_buffer

    def save_buffer_to_wav(self, audio_buffer, filename: str) -> None:
        """Save numpy audio buffer to a WAV file."""

        with wave.open(filename, "wb") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(self.sample_rate)
            wf.writeframes(audio_buffer.tobytes())

    def stop_stream(self) -> None:
        """Stop capture and terminate FFmpeg."""

        self.is_streaming = False

        if self.ffmpeg_process:
            self.ffmpeg_process.terminate()
            try:
                self.ffmpeg_process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.ffmpeg_process.kill()
                self.ffmpeg_process.wait()
            self.ffmpeg_process = None

        print("⏹️  Stream capture stopped")

    def __del__(self) -> None:
        self.stop_stream()


# Backward compatibility for imports and tests
LiveTwitchAudioCapture = LiveStreamAudioCapture
