# Code Generated by Sidekick is for learning and experimentation purposes only.
# question_extractor.py
import openai
import re
from typing import Optional, Dict

class QuestionExtractor:
    def __init__(self, api_key: str):
        self.client = openai.OpenAI(api_key=api_key)
        
    def extract_question_info(self, transcribed_text: str) -> Dict:
        """
        Use GPT to extract:
        - Question number
        - Hour number
        - The actual question text
        - Whether it's a picture question
        """
        
        prompt = f"""You are analyzing trivia contest audio transcription. Extract the following:

1. Question number (if mentioned, e.g., "question 5")
2. Hour number (if mentioned, e.g., "of hour 2")
3. The actual trivia question (the full question being asked)
4. Is this a picture question? (yes/no)

Transcribed text:
"{transcribed_text}"

Respond in this exact JSON format:
{{
    "question_number": <int or null>,
    "hour_number": <int or null>,
    "question_text": "<the actual question>",
    "is_picture_question": <true or false>,
    "confidence": "<high/medium/low>"
}}

If no clear question is detected, set question_text to null."""

        response = self.client.chat.completions.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            response_format={"type": "json_object"}
        )
        
        import json
        result = json.loads(response.choices[0].message.content)
        
        # Fallback: Try regex for question/hour numbers if LLM missed them
        if not result.get("question_number"):
            question_match = re.search(r'question\s+(\d+)', transcribed_text, re.IGNORECASE)
            if question_match:
                result["question_number"] = int(question_match.group(1))
                
        if not result.get("hour_number"):
            hour_match = re.search(r'hour\s+(\d+)', transcribed_text, re.IGNORECASE)
            if hour_match:
                result["hour_number"] = int(hour_match.group(1))
        
        return result
    
    def is_duplicate(self, new_question: str, recent_questions: list, 
                     similarity_threshold: float = 0.85) -> bool:
        """
        Check if this question is a duplicate (repeated reading)
        Uses simple word overlap ratio
        """
        if not recent_questions:
            return False
        
        new_words = set(new_question.lower().split())
        
        for recent_q in recent_questions[-3:]:  # Check last 3 questions
            recent_words = set(recent_q.lower().split())
            
            # Calculate Jaccard similarity
            intersection = len(new_words & recent_words)
            union = len(new_words | recent_words)
            
            if union > 0:
                similarity = intersection / union
                if similarity >= similarity_threshold:
                    return True
        
        return False
