# Code Generated by Sidekick is for learning and experimentation purposes only.
# sliding_window_processor.py
import threading
import time
from collections import deque
from collections.abc import Callable
from datetime import datetime
from typing import Optional

from utils.logger import setup_logger, setup_transcription_logger

logger = setup_logger(__name__)
transcription_logger = setup_transcription_logger()

# Shown in the web UI when a window has no usable audio or no speech detected (API SSE).
NO_AUDIO_CHUNK_MESSAGE = "[no audio this chunk]"


class SlidingWindowProcessor:
    def __init__(
        self,
        stream_capture,
        transcriber,
        extractor,
        excel_manager,
        audio_window_seconds=30,
        segment_interval_seconds=15,
        on_transcription: Optional[Callable[[str], None]] = None,
        enable_question_extraction: bool = True,
    ):
        """Process overlapping audio windows from a live stream.

        Args:
            stream_capture: Source of raw audio (e.g. live Twitch capture).
            transcriber: Component that turns audio buffers into text.
            extractor: LLM-backed extractor for structured question fields.
                       Ignored when ``enable_question_extraction`` is False.
            excel_manager: Persists extracted questions.
                           Ignored when ``enable_question_extraction`` is False.
            audio_window_seconds: Seconds of audio captured per Whisper window.
            segment_interval_seconds: Seconds between each new transcription being triggered.
            on_transcription: Optional callback invoked with each non-duplicate
                transcription text after the minimum-length filter, before
                question extraction. Also invoked with ``NO_AUDIO_CHUNK_MESSAGE``
                when a window has no audio buffer or no usable speech.
            enable_question_extraction: When False the LLM extraction step and
                Excel persistence are skipped entirely; only transcription and
                the ``on_transcription`` callback run.
        """
        self.stream_capture = stream_capture
        self.transcriber = transcriber
        self.extractor = extractor
        self.excel_manager = excel_manager
        self.enable_question_extraction = enable_question_extraction

        self.audio_window_seconds = audio_window_seconds
        self.segment_interval_seconds = segment_interval_seconds
        self.on_transcription = on_transcription
        
        self.is_processing = False
        self.processing_thread = None
        
        # Track recent transcriptions to detect duplicates
        self.recent_transcriptions = deque(maxlen=5)
        self.recent_questions = deque(maxlen=5)
        
        self.current_hour = 1
        self.question_count = 0
        
    def start_processing(self):
        """Start continuous processing of live stream"""
        self.is_processing = True
        self.processing_thread = threading.Thread(target=self._processing_loop, daemon=True)
        self.processing_thread.start()
        logger.info("Started live stream processing")
    
    def _processing_loop(self):
        """Main processing loop - runs continuously"""
        last_process_time = time.time()
        
        while self.is_processing:
            current_time = time.time()
            
            # Trigger a new transcription every segment_interval_seconds
            if current_time - last_process_time >= self.segment_interval_seconds:
                try:
                    self._process_window()
                    last_process_time = current_time
                except Exception as e:
                    logger.error(f"Error processing window: {e}")
            
            time.sleep(0.5)  # Small sleep to prevent busy waiting
    
    def _process_window(self):
        """Process one window of audio"""
        logger.info(f"Processing {self.audio_window_seconds}s audio window...")
        
        # Get audio buffer from stream
        audio_buffer = self.stream_capture.get_audio_buffer(self.audio_window_seconds)
        
        if audio_buffer is None or len(audio_buffer) == 0:
            logger.warning("No audio data available")
            if self.on_transcription is not None:
                self.on_transcription(NO_AUDIO_CHUNK_MESSAGE)
            return

        # Transcribe
        start_time = time.time()
        transcription = self.transcriber.transcribe_audio_buffer(audio_buffer)
        transcribe_time = time.time() - start_time

        if not transcription or len(transcription.strip()) < 20:
            # Too short, probably just music or silence
            if self.on_transcription is not None:
                self.on_transcription(NO_AUDIO_CHUNK_MESSAGE)
            return
        
        logger.info(f"Transcribed ({transcribe_time:.1f}s): {transcription[:80]}...")
        transcription_logger.info(transcription)
        
        # Check if this is a duplicate of recent transcription (repeated question)
        if self._is_duplicate_transcription(transcription):
            logger.info("Duplicate transcription detected (skipping)")
            return

        self.recent_transcriptions.append(transcription)
        if self.on_transcription is not None:
            self.on_transcription(transcription)

        if not self.enable_question_extraction:
            return

        # Extract question information using LLM
        question_info = self.extractor.extract_question_info(transcription)
        
        # Check if valid question was found
        if not question_info.get("question_text"):
            logger.debug("No question detected in this window")
            return
        
        logger.info(f"Question detected: {question_info['question_text'][:60]}...")
        # Update hour if specified
        if question_info.get("hour_number"):
            if question_info["hour_number"] != self.current_hour:
                self.current_hour = question_info["hour_number"]
                self.question_count = 0
                logger.info(f"Switched to Hour {self.current_hour}")

        # Check if this question was already saved
        if self._is_duplicate_question(question_info["question_text"]):
            logger.info("Question already saved (skipping)")
            return
        
        self.recent_questions.append(question_info["question_text"])
        
        # Determine question number
        if question_info.get("question_number"):
            q_num = question_info["question_number"]
        else:
            self.question_count += 1
            q_num = self.question_count
        
        # Save to Excel
        self.excel_manager.add_question(
            hour_number=self.current_hour,
            question_number=q_num,
            question_text=question_info["question_text"],
            song="",  # Can be filled manually or detected separately
            is_picture_question=question_info.get("is_picture_question", False)
        )
        
        logger.info(f"Saved: Hour {self.current_hour}, Question {q_num}")
    
    def _is_duplicate_transcription(self, new_transcription):
        """Check if this transcription is very similar to recent ones"""
        new_words = set(new_transcription.lower().split())
        
        for recent in self.recent_transcriptions:
            recent_words = set(recent.lower().split())
            
            # Jaccard similarity
            intersection = len(new_words & recent_words)
            union = len(new_words | recent_words)
            
            if union > 0:
                similarity = intersection / union
                if similarity > 0.80:  # 80% similar = duplicate
                    return True
        
        return False
    
    def _is_duplicate_question(self, question_text):
        """Check if this question was already saved"""
        question_words = set(question_text.lower().split())
        
        for recent_q in self.recent_questions:
            recent_words = set(recent_q.lower().split())
            
            intersection = len(question_words & recent_words)
            union = len(question_words | recent_words)
            
            if union > 0:
                similarity = intersection / union
                if similarity > 0.85:  # 85% similar = duplicate
                    return True
        
        return False
    
    def stop_processing(self):
        """Stop processing"""
        self.is_processing = False
        if self.processing_thread:
            self.processing_thread.join(timeout=5)
        logger.info("Stopped processing")
    
    def set_hour(self, hour_number):
        """Manually set current hour"""
        self.current_hour = hour_number
        self.question_count = 0
        logger.info(f"Hour manually set to: {hour_number}")
