# Code Generated by Sidekick is for learning and experimentation purposes only.
# sliding_window_processor.py
import threading
import time
from collections import deque
from datetime import datetime

class SlidingWindowProcessor:
    def __init__(self, stream_capture, transcriber, extractor, excel_manager,
                 window_duration=30, overlap_duration=15):
        """
        window_duration: seconds of audio to process at once (30s covers full question)
        overlap_duration: seconds of overlap between windows (50% = 15s)
        """
        self.stream_capture = stream_capture
        self.transcriber = transcriber
        self.extractor = extractor
        self.excel_manager = excel_manager
        
        self.window_duration = window_duration
        self.overlap_duration = overlap_duration
        
        self.is_processing = False
        self.processing_thread = None
        
        # Track recent transcriptions to detect duplicates
        self.recent_transcriptions = deque(maxlen=5)
        self.recent_questions = deque(maxlen=5)
        
        self.current_hour = 1
        self.question_count = 0
        
    def start_processing(self):
        """Start continuous processing of live stream"""
        self.is_processing = True
        self.processing_thread = threading.Thread(target=self._processing_loop, daemon=True)
        self.processing_thread.start()
        print("🎬 Started live stream processing")
    
    def _processing_loop(self):
        """Main processing loop - runs continuously"""
        last_process_time = time.time()
        
        while self.is_processing:
            current_time = time.time()
            
            # Process every overlap_duration seconds
            if current_time - last_process_time >= self.overlap_duration:
                try:
                    self._process_window()
                    last_process_time = current_time
                except Exception as e:
                    print(f"❌ Error processing window: {e}")
            
            time.sleep(0.5)  # Small sleep to prevent busy waiting
    
    def _process_window(self):
        """Process one window of audio"""
        print(f"\n⏳ Processing {self.window_duration}s audio window...")
        
        # Get audio buffer from stream
        audio_buffer = self.stream_capture.get_audio_buffer(self.window_duration)
        
        if audio_buffer is None or len(audio_buffer) == 0:
            print("⚠️  No audio data available")
            return
        
        # Transcribe
        start_time = time.time()
        transcription = self.transcriber.transcribe_audio_buffer(audio_buffer)
        transcribe_time = time.time() - start_time
        
        if not transcription or len(transcription.strip()) < 20:
            # Too short, probably just music or silence
            return
        
        print(f"📝 Transcribed ({transcribe_time:.1f}s): {transcription[:80]}...")
        
        # Check if this is a duplicate of recent transcription (repeated question)
        if self._is_duplicate_transcription(transcription):
            print("⏭️  Duplicate transcription detected (skipping)")
            return
        
        self.recent_transcriptions.append(transcription)
        
        # Extract question information using LLM
        question_info = self.extractor.extract_question_info(transcription)
        
        # Check if valid question was found
        if not question_info.get("question_text"):
            print("   No question detected in this window")
            return
        
        print(f"✅ Question detected: {question_info['question_text'][:60]}...")
        
        # Update hour if specified
        if question_info.get("hour_number"):
            if question_info["hour_number"] != self.current_hour:
                self.current_hour = question_info["hour_number"]
                self.question_count = 0
                print(f"📍 Switched to Hour {self.current_hour}")
        
        # Check if this question was already saved
        if self._is_duplicate_question(question_info["question_text"]):
            print("⏭️  Question already saved (skipping)")
            return
        
        self.recent_questions.append(question_info["question_text"])
        
        # Determine question number
        if question_info.get("question_number"):
            q_num = question_info["question_number"]
        else:
            self.question_count += 1
            q_num = self.question_count
        
        # Save to Excel
        self.excel_manager.add_question(
            hour_number=self.current_hour,
            question_number=q_num,
            question_text=question_info["question_text"],
            song="",  # Can be filled manually or detected separately
            is_picture_question=question_info.get("is_picture_question", False)
        )
        
        print(f"💾 Saved: Hour {self.current_hour}, Question {q_num}")
    
    def _is_duplicate_transcription(self, new_transcription):
        """Check if this transcription is very similar to recent ones"""
        new_words = set(new_transcription.lower().split())
        
        for recent in self.recent_transcriptions:
            recent_words = set(recent.lower().split())
            
            # Jaccard similarity
            intersection = len(new_words & recent_words)
            union = len(new_words | recent_words)
            
            if union > 0:
                similarity = intersection / union
                if similarity > 0.80:  # 80% similar = duplicate
                    return True
        
        return False
    
    def _is_duplicate_question(self, question_text):
        """Check if this question was already saved"""
        question_words = set(question_text.lower().split())
        
        for recent_q in self.recent_questions:
            recent_words = set(recent_q.lower().split())
            
            intersection = len(question_words & recent_words)
            union = len(question_words | recent_words)
            
            if union > 0:
                similarity = intersection / union
                if similarity > 0.85:  # 85% similar = duplicate
                    return True
        
        return False
    
    def stop_processing(self):
        """Stop processing"""
        self.is_processing = False
        if self.processing_thread:
            self.processing_thread.join(timeout=5)
        print("⏹️  Stopped processing")
    
    def set_hour(self, hour_number):
        """Manually set current hour"""
        self.current_hour = hour_number
        self.question_count = 0
        print(f"📍 Hour manually set to: {hour_number}")
