# Code Generated by Sidekick is for learning and experimentation purposes only.
# streaming_transcription.py
from faster_whisper import WhisperModel
import numpy as np
import tempfile
import os

class StreamingTranscriber:
    def __init__(self, model_size="base", device="cpu"):
        """
        Initialize Faster-Whisper model (much faster than openai-whisper)
        model_size: tiny, base, small, medium, large-v2
        device: "cpu" or "cuda"
        
        For live streaming, "base" is recommended (good balance of speed/accuracy)
        """
        print(f"Loading Faster-Whisper model: {model_size} on {device}...")
        
        # Use int8 for faster inference on CPU
        compute_type = "int8" if device == "cpu" else "float16"
        
        self.model = WhisperModel(
            model_size,
            device=device,
            compute_type=compute_type,
            num_workers=4  # Parallel processing
        )
        
        print("✓ Transcription model loaded")
        
    def transcribe_audio_buffer(self, audio_buffer, sample_rate=16000):
        """
        Transcribe numpy audio buffer directly
        audio_buffer: numpy array of int16 samples
        """
        # Convert int16 to float32 (Whisper expects float32 between -1 and 1)
        audio_float = audio_buffer.astype(np.float32) / 32768.0
        
        # Transcribe
        segments, info = self.model.transcribe(
            audio_float,
            language="en",
            beam_size=5,
            vad_filter=True,  # Voice Activity Detection - skip silence
            vad_parameters=dict(
                threshold=0.5,
                min_speech_duration_ms=250,
                max_speech_duration_s=float('inf'),
                min_silence_duration_ms=100,
                speech_pad_ms=400
            )
        )
        
        # Combine all segments
        full_text = " ".join([segment.text for segment in segments]).strip()
        
        return full_text
    
    def transcribe_with_timestamps(self, audio_buffer, sample_rate=16000):
        """
        Returns transcription with word-level timestamps
        Useful for detecting when questions start/end
        """
        audio_float = audio_buffer.astype(np.float32) / 32768.0
        
        segments, info = self.model.transcribe(
            audio_float,
            language="en",
            beam_size=5,
            word_timestamps=True,
            vad_filter=True
        )
        
        result = {
            "full_text": "",
            "segments": []
        }
        
        for segment in segments:
            segment_data = {
                "text": segment.text,
                "start": segment.start,
                "end": segment.end,
                "words": []
            }
            
            if hasattr(segment, 'words'):
                segment_data["words"] = [
                    {"word": w.word, "start": w.start, "end": w.end}
                    for w in segment.words
                ]
            
            result["segments"].append(segment_data)
            result["full_text"] += segment.text + " "
        
        result["full_text"] = result["full_text"].strip()
        return result
