# Code Generated by Sidekick is for learning and experimentation purposes only.
# Simple Tkinter GUI
import tkinter as tk
from tkinter import ttk

class StatusGUI:
    def __init__(self, processor):
        self.processor = processor
        self.root = tk.Tk()
        self.root.title("Live Trivia Assistant")
        
        # Status labels
        self.hour_label = ttk.Label(self.root, text="Hour: 1", font=("Arial", 16))
        self.hour_label.pack(pady=10)
        
        self.questions_label = ttk.Label(self.root, text="Questions: 0", font=("Arial", 14))
        self.questions_label.pack()
        
        self.status_label = ttk.Label(self.root, text="● LIVE", foreground="green")
        self.status_label.pack(pady=20)
        
        # Update every second
        self.update_status()
        
    def update_status(self):
        self.hour_label.config(text=f"Hour: {self.processor.current_hour}")
        self.questions_label.config(text=f"Questions: {self.processor.question_count}")
        self.root.after(1000, self.update_status)
    
    def run(self):
        self.root.mainloop()
