# Code Generated by Sidekick is for learning and experimentation purposes only.
"""FastAPI application: start/stop live transcription and SSE stream."""
from __future__ import annotations

import asyncio
import os
import queue
import threading
from pathlib import Path
from typing import Any, AsyncIterator

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from starlette.staticfiles import StaticFiles

from config import Config
from core import LiveTriviaAssistant
from schemas import (
    HealthResponse,
    SessionConfigResponse,
    StartSessionRequest,
    StartSessionResponse,
    StopSessionResponse,
    TranscriptionEvent,
)
from utils.logger import setup_logger

logger = setup_logger(__name__)

# Sentinel placed on the SSE queue so clients end the stream after stop.
_SSE_STOP: Any = object()


class SessionAlreadyRunningError(Exception):
    """Raised when ``/api/start`` is called while a session exists."""


class SessionNotRunningError(Exception):
    """Raised when ``/api/stop`` is called with no active session."""


class _SessionState:
    """In-process session: one Twitch pipeline and one event queue for SSE."""

    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.assistant: LiveTriviaAssistant | None = None
        self.event_queue: queue.Queue[str | Any] | None = None


_state = _SessionState()


def _cors_allow_origins() -> list[str]:
    """Origins allowed for browser CORS (JSON POST and SSE preflight).

    Includes localhost, Render's public service URL when ``RENDER_EXTERNAL_URL`` is set
    (injected by Render), and any extra origins from ``CORS_ORIGINS`` (comma-separated).
    Origins must match the browser's ``Origin`` header exactly (scheme + host, no path;
    no trailing slash).

    Returns:
        List of origin strings, no duplicates.
    """
    seeds = [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
    ]
    render_public = os.getenv("RENDER_EXTERNAL_URL", "").strip().rstrip("/")
    if render_public:
        seeds.append(render_public)

    extra_raw = os.getenv("CORS_ORIGINS", "").strip()
    extras = (
        [o.strip().rstrip("/") for o in extra_raw.split(",") if o.strip()]
        if extra_raw
        else []
    )

    seen: set[str] = set()
    ordered: list[str] = []
    for origin in seeds + extras:
        if origin not in seen:
            seen.add(origin)
            ordered.append(origin)
    return ordered


def _frontend_dir() -> Path:
    """Resolve the directory containing static web assets.

    Returns:
        pathlib.Path: Absolute path to ``trivia_application/frontend``.
    """
    return Path(__file__).resolve().parent.parent / "frontend"


def _sync_start(url: str) -> None:
    """Create assistant, wire transcription callback, and start capture under lock.

    Args:
        url: Validated Twitch channel URL.

    Raises:
        SessionAlreadyRunningError: If a session is already active.
        Exception: Any error from ``LiveTriviaAssistant.start()`` (after rollback).
    """
    with _state.lock:
        if _state.assistant is not None:
            raise SessionAlreadyRunningError()

        event_queue: queue.Queue[str | Any] = queue.Queue(maxsize=500)
        _state.event_queue = event_queue

        def on_transcription(text: str) -> None:
            try:
                payload = TranscriptionEvent(text=text).model_dump_json()
                event_queue.put_nowait(payload)
            except queue.Full:
                logger.warning("Transcription event queue full; dropping one event")
            except Exception:
                logger.exception("Failed to enqueue transcription event")

        assistant = LiveTriviaAssistant(
            url,
            on_transcription=on_transcription,
            quiet=True,
        )
        _state.assistant = assistant

        try:
            assistant.start()
        except Exception:
            _state.assistant = None
            _state.event_queue = None
            raise


def _sync_stop() -> None:
    """Stop assistant and signal SSE consumers with a sentinel.

    Raises:
        SessionNotRunningError: If no session exists.
    """
    with _state.lock:
        assistant = _state.assistant
        event_queue = _state.event_queue
        _state.assistant = None
        _state.event_queue = None

    if assistant is None:
        raise SessionNotRunningError()

    try:
        assistant.stop()
    finally:
        if event_queue is not None:
            try:
                event_queue.put_nowait(_SSE_STOP)
            except queue.Full:
                logger.warning("Could not enqueue SSE stop sentinel; queue full")


async def _sse_event_generator(
    q: queue.Queue[str | Any],
) -> AsyncIterator[str]:
    """Yield Server-Sent Events lines until stop sentinel or client disconnect.

    Client disconnect cancels the async iterator (Starlette).

    Args:
        q: Queue populated with JSON strings or ``_SSE_STOP``.

    Yields:
        str: Lines including ``data:`` payloads for SSE.
    """
    loop = asyncio.get_running_loop()

    def _get_item(timeout: float) -> str | Any | None:
        try:
            return q.get(timeout=timeout)
        except queue.Empty:
            return None

    while True:
        item = await loop.run_in_executor(None, _get_item, 1.0)
        if item is None:
            continue
        if item is _SSE_STOP:
            break
        yield f"data: {item}\n\n"


def create_app() -> FastAPI:
    """Build and configure the FastAPI application (routes + static files).

    Returns:
        fastapi.FastAPI: Configured app instance.
    """
    app = FastAPI(title="Trivia Transcription API", version="0.1.0")

    app.add_middleware(
        CORSMiddleware,
        allow_origins=_cors_allow_origins(),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/health", response_model=HealthResponse)
    def health() -> HealthResponse:
        """Liveness check for load balancers and operators.

        Returns:
            HealthResponse: Fixed OK payload.
        """
        return HealthResponse()

    @app.get("/api/config", response_model=SessionConfigResponse)
    def api_config() -> SessionConfigResponse:
        """Return processing timing values so the frontend can drive the progress bar.

        Returns:
            SessionConfigResponse: Window and overlap durations in seconds.
        """
        return SessionConfigResponse(
            window_duration=Config.WINDOW_DURATION,
            overlap_duration=Config.OVERLAP_DURATION,
        )

    @app.post("/api/start", response_model=StartSessionResponse)
    async def api_start(body: StartSessionRequest) -> StartSessionResponse:
        """Start capturing and transcribing the given Twitch channel.

        Args:
            body: Parsed JSON body with ``twitch_url``.

        Returns:
            StartSessionResponse: Confirmation payload.

        Raises:
            HTTPException: 409 if a session exists; 500 on unexpected start errors.
        """
        try:
            await asyncio.to_thread(_sync_start, body.twitch_url)
        except SessionAlreadyRunningError:
            raise HTTPException(
                status_code=409,
                detail="A transcription session is already running. Stop it first.",
            )
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except Exception as exc:
            logger.exception("Failed to start session")
            raise HTTPException(
                status_code=500,
                detail="Failed to start session. Check logs and Twitch URL.",
            ) from exc

        return StartSessionResponse(
            status="started",
            message="Live capture and transcription are running. First Whisper load may take a while.",
        )

    @app.post("/api/stop", response_model=StopSessionResponse)
    async def api_stop() -> StopSessionResponse:
        """Stop the current session and release stream resources.

        Returns:
            StopSessionResponse: Confirmation payload.

        Raises:
            HTTPException: If no session is active (400).
        """
        try:
            await asyncio.to_thread(_sync_stop)
        except SessionNotRunningError:
            raise HTTPException(
                status_code=400,
                detail="No active session to stop.",
            )

        return StopSessionResponse(status="stopped", message="Session stopped.")

    @app.get("/api/transcription/stream")
    async def api_transcription_stream() -> StreamingResponse:
        """Stream transcription events as Server-Sent Events (JSON per line).

        Returns:
            StreamingResponse: ``text/event-stream`` body.

        Raises:
            HTTPException: If no session is active (503).
        """
        with _state.lock:
            q = _state.event_queue

        if q is None:
            raise HTTPException(
                status_code=503,
                detail="No active session. POST /api/start first.",
            )

        return StreamingResponse(
            _sse_event_generator(q),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
            },
        )

    static_root = _frontend_dir()
    if static_root.is_dir():
        app.mount(
            "/",
            StaticFiles(directory=str(static_root), html=True),
            name="frontend",
        )
    else:
        logger.warning("Frontend directory missing at %s; static UI not mounted", static_root)

    return app


app = create_app()
