# Code Generated by Sidekick is for learning and experimentation purposes only.
# config.py
"""
Configuration settings for Trivia Transcription Assistant
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Load backend/.env regardless of current working directory (e.g. repo root vs backend/).
load_dotenv(Path(__file__).resolve().parent / ".env")

class Config:
    # API Keys
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    
    # Twitch Settings
    TWITCH_CHANNEL_URL = os.getenv(
        "TWITCH_CHANNEL_URL", "https://m.twitch.tv/neglagonave"
    )
    
    # Audio Settings
    SAMPLE_RATE = 16000  # Hz - optimal for Whisper
    AUDIO_CHANNELS = 1   # Mono
    
    # Whisper Settings
    WHISPER_MODEL_SIZE = os.getenv("WHISPER_MODEL_SIZE", "base")
    WHISPER_DEVICE = os.getenv("WHISPER_DEVICE", "cpu")
    WHISPER_COMPUTE_TYPE = "int8" if WHISPER_DEVICE == "cpu" else "float16"
    
    # Processing Settings
    WINDOW_DURATION = int(os.getenv("WINDOW_DURATION", 30))  # seconds
    OVERLAP_DURATION = int(os.getenv("OVERLAP_DURATION", 15))  # seconds
    
    # Deduplication Thresholds
    TRANSCRIPTION_SIMILARITY_THRESHOLD = 0.80  # 80% = duplicate transcription
    QUESTION_SIMILARITY_THRESHOLD = 0.85       # 85% = duplicate question
    
    # Queue Settings
    MAX_AUDIO_QUEUE_SIZE = 100  # Maximum audio chunks in memory
    
    # Excel Settings
    EXCEL_FILENAME = "data/trivia_questions.xlsx"
    
    # Logging
    LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
    LOG_DIR = "logs/app"
    TRANSCRIPTION_LOG_DIR = "logs/transcriptions"
    
    # Paths
    TEMP_AUDIO_DIR = "data/temp"
    
    @classmethod
    def _ensure_data_dirs(cls):
        """Create standard data and log directories if missing."""
        os.makedirs("data", exist_ok=True)
        os.makedirs("data/temp", exist_ok=True)
        os.makedirs(cls.LOG_DIR, exist_ok=True)
        os.makedirs(cls.TRANSCRIPTION_LOG_DIR, exist_ok=True)

    @classmethod
    def validate(cls):
        """Validate configuration for the CLI assistant (requires Twitch URL in env)."""
        if not cls.OPENAI_API_KEY:
            raise ValueError("OPENAI_API_KEY not set in .env file")

        if not cls.TWITCH_CHANNEL_URL:
            raise ValueError("TWITCH_CHANNEL_URL not set in .env file")

        cls._ensure_data_dirs()

        return True

    @classmethod
    def validate_for_api(cls):
        """Validate configuration for the FastAPI server.

        Requires ``OPENAI_API_KEY`` only; Twitch channel URL is supplied per request.
        Ensures data and log directories exist.

        Returns:
            bool: ``True`` if validation succeeded.

        Raises:
            ValueError: If ``OPENAI_API_KEY`` is missing from the environment.
        """
        if not cls.OPENAI_API_KEY:
            raise ValueError("OPENAI_API_KEY not set in .env file")

        cls._ensure_data_dirs()

        return True
