# Code Generated by Sidekick is for learning and experimentation purposes only.
# config.py
"""
Configuration settings for Trivia Transcription Assistant
"""
import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    # API Keys
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    
    # Twitch Settings
    TWITCH_CHANNEL_URL = os.getenv("TWITCH_CHANNEL_URL", "")
    
    # Audio Settings
    SAMPLE_RATE = 16000  # Hz - optimal for Whisper
    AUDIO_CHANNELS = 1   # Mono
    
    # Whisper Settings
    WHISPER_MODEL_SIZE = os.getenv("WHISPER_MODEL_SIZE", "base")
    WHISPER_DEVICE = os.getenv("WHISPER_DEVICE", "cpu")
    WHISPER_COMPUTE_TYPE = "int8" if WHISPER_DEVICE == "cpu" else "float16"
    
    # Processing Settings
    WINDOW_DURATION = int(os.getenv("WINDOW_DURATION", 30))  # seconds
    OVERLAP_DURATION = int(os.getenv("OVERLAP_DURATION", 15))  # seconds
    
    # Deduplication Thresholds
    TRANSCRIPTION_SIMILARITY_THRESHOLD = 0.80  # 80% = duplicate transcription
    QUESTION_SIMILARITY_THRESHOLD = 0.85       # 85% = duplicate question
    
    # Queue Settings
    MAX_AUDIO_QUEUE_SIZE = 100  # Maximum audio chunks in memory
    
    # Excel Settings
    EXCEL_FILENAME = "data/trivia_questions.xlsx"
    
    # Logging
    LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
    LOG_FILE = "logs/trivia_assistant.log"
    
    # Paths
    TEMP_AUDIO_DIR = "data/temp"
    
    @classmethod
    def validate(cls):
        """Validate configuration"""
        if not cls.OPENAI_API_KEY:
            raise ValueError("OPENAI_API_KEY not set in .env file")
        
        if not cls.TWITCH_CHANNEL_URL:
            raise ValueError("TWITCH_CHANNEL_URL not set in .env file")
        
        # Create directories if they don't exist
        os.makedirs("data", exist_ok=True)
        os.makedirs("data/temp", exist_ok=True)
        os.makedirs("logs", exist_ok=True)
        
        return True
