# Code Generated by Sidekick is for learning and experimentation purposes only.
# config.py
"""
Configuration settings for Trivia Transcription Assistant
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Load backend/.env regardless of current working directory (e.g. repo root vs backend/).
load_dotenv(Path(__file__).resolve().parent / ".env")

class Config:
    # API Keys
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    
    # Twitch Settings
    TWITCH_CHANNEL_URL = os.getenv(
        "TWITCH_CHANNEL_URL", "https://m.twitch.tv/neglagonave"
    )
    
    # Audio Settings
    SAMPLE_RATE = 16000  # Hz - optimal for Whisper
    AUDIO_CHANNELS = 1   # Mono
    
    # Whisper Settings
    WHISPER_MODEL_SIZE = os.getenv("WHISPER_MODEL_SIZE", "base")
    WHISPER_DEVICE = os.getenv("WHISPER_DEVICE", "cpu")
    WHISPER_COMPUTE_TYPE = "int8" if WHISPER_DEVICE == "cpu" else "float16"
    
    # Processing Settings
    # AUDIO_WINDOW_SECONDS must always be greater than SEGMENT_INTERVAL_SECONDS.
    # The difference (AUDIO_WINDOW_SECONDS - SEGMENT_INTERVAL_SECONDS) is the
    # audio overlap shared between consecutive windows.
    AUDIO_WINDOW_SECONDS = int(os.getenv("AUDIO_WINDOW_SECONDS", 30))          # larger  — seconds of audio captured per Whisper window
    SEGMENT_INTERVAL_SECONDS = int(os.getenv("SEGMENT_INTERVAL_SECONDS", 15))  # smaller — seconds between each new transcription
    
    # Feature Flags
    # Set to False (or ENABLE_QUESTION_EXTRACTION=false in .env) to skip the
    # second LLM call that extracts structured question fields from transcriptions.
    # Useful for testing the audio capture → transcription → UI display pipeline.
    ENABLE_QUESTION_EXTRACTION: bool = (
        os.getenv("ENABLE_QUESTION_EXTRACTION", "false").lower() not in ("0", "false", "no")
    )

    # Deduplication Thresholds
    TRANSCRIPTION_SIMILARITY_THRESHOLD = 0.80  # 80% = duplicate transcription
    QUESTION_SIMILARITY_THRESHOLD = 0.85       # 85% = duplicate question
    
    # Queue Settings
    MAX_AUDIO_QUEUE_SIZE = 100  # Maximum audio chunks in memory
    
    # Excel Settings
    EXCEL_FILENAME = "data/trivia_questions.xlsx"
    
    # Logging
    LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
    LOG_DIR = "logs/app"
    TRANSCRIPTION_LOG_DIR = "logs/transcriptions"
    
    # Paths
    TEMP_AUDIO_DIR = "data/temp"
    
    @classmethod
    def _ensure_data_dirs(cls):
        """Create standard data and log directories if missing."""
        os.makedirs("data", exist_ok=True)
        os.makedirs("data/temp", exist_ok=True)
        os.makedirs(cls.LOG_DIR, exist_ok=True)
        os.makedirs(cls.TRANSCRIPTION_LOG_DIR, exist_ok=True)

    @classmethod
    def validate(cls):
        """Validate configuration for the CLI assistant (requires Twitch URL in env)."""
        if cls.ENABLE_QUESTION_EXTRACTION and not cls.OPENAI_API_KEY:
            raise ValueError(
                "OPENAI_API_KEY not set in .env file "
                "(required when ENABLE_QUESTION_EXTRACTION=true)"
            )

        if not cls.TWITCH_CHANNEL_URL:
            raise ValueError("TWITCH_CHANNEL_URL not set in .env file")

        cls._ensure_data_dirs()

        return True

    @classmethod
    def log_config(cls) -> None:
        """Log all effective configuration values (API key masked)."""
        import logging
        logger = logging.getLogger(__name__)
        api_key = cls.OPENAI_API_KEY
        masked = f"{api_key[:8]}..." if api_key else "(not set)"
        logger.info("Config: OPENAI_API_KEY=%s", masked)
        logger.info(
            "Config: WHISPER_MODEL_SIZE=%s  WHISPER_DEVICE=%s  WHISPER_COMPUTE_TYPE=%s",
            cls.WHISPER_MODEL_SIZE, cls.WHISPER_DEVICE, cls.WHISPER_COMPUTE_TYPE,
        )
        logger.info(
            "Config: AUDIO_WINDOW_SECONDS=%s  SEGMENT_INTERVAL_SECONDS=%s",
            cls.AUDIO_WINDOW_SECONDS, cls.SEGMENT_INTERVAL_SECONDS,
        )
        logger.info("Config: ENABLE_QUESTION_EXTRACTION=%s", cls.ENABLE_QUESTION_EXTRACTION)
        logger.info("Config: LOG_LEVEL=%s", cls.LOG_LEVEL)
        logger.info("Config: TWITCH_CHANNEL_URL=%s", cls.TWITCH_CHANNEL_URL or "(not set)")

    @classmethod
    def validate_for_api(cls):
        """Validate configuration for the FastAPI server.

        Requires ``OPENAI_API_KEY`` only when ``ENABLE_QUESTION_EXTRACTION`` is
        ``True``; Twitch channel URL is supplied per request.
        Ensures data and log directories exist.

        Returns:
            bool: ``True`` if validation succeeded.

        Raises:
            ValueError: If ``OPENAI_API_KEY`` is missing and extraction is enabled.
        """
        if cls.ENABLE_QUESTION_EXTRACTION and not cls.OPENAI_API_KEY:
            raise ValueError(
                "OPENAI_API_KEY not set in .env file "
                "(required when ENABLE_QUESTION_EXTRACTION=true)"
            )

        cls._ensure_data_dirs()

        return True
