# Code Generated by Sidekick is for learning and experimentation purposes only.
# main.py
"""
Main entry point for Trivia Transcription Assistant
"""
import sys
from config import Config
from core import LiveTriviaAssistant
from utils.logger import setup_logger

def main():
    """Main function"""
    # Validate configuration
    try:
        Config.validate()
    except ValueError as e:
        print(f"❌ Configuration Error: {e}")
        print("\nPlease check your .env file and ensure all required settings are present.")
        sys.exit(1)
    
    # Setup logging
    logger = setup_logger()
    
    # Create and run assistant
    logger.info("Starting Trivia Transcription Assistant")
    
    try:
        assistant = LiveTriviaAssistant(Config.TWITCH_CHANNEL_URL)
        assistant.run_interactive()
    except KeyboardInterrupt:
        logger.info("Application interrupted by user")
        print("\n👋 Goodbye!")
    except Exception as e:
        logger.error(f"Fatal error: {e}", exc_info=True)
        print(f"\n❌ Fatal Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
