# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Shared question log (hour + question number → text): in-memory or SQLAlchemy (Postgres/SQLite)."""
from __future__ import annotations

import threading
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional

from sqlalchemy import delete, select

from question_log_db import (
    QuestionLogRow,
    create_engine_for_url,
    init_schema,
    make_session_factory,
)

if TYPE_CHECKING:
    from sqlalchemy.engine import Engine
    from sqlalchemy.orm import Session, sessionmaker

_lock = threading.Lock()
_memory: dict[tuple[int, int], LoggedQuestionEntry] = {}

_engine: Optional[Engine] = None
_SessionLocal: Optional[sessionmaker[Session]] = None
_use_database: bool = False
_configured_url: Optional[str] = None


@dataclass(frozen=True)
class LoggedQuestionEntry:
    """One stored question keyed by hour and question index."""

    hour: int
    question_number: int
    text: str
    updated_at: str


def configure(database_url: str | None) -> None:
    """Switch persistence backend (call once at app startup from ``Config``).

    Args:
        database_url: PostgreSQL or SQLite URL, or ``None`` / empty for in-memory only.

    Raises:
        ValueError: If the URL is invalid for SQLAlchemy.
    """

    global _engine, _SessionLocal, _use_database, _configured_url

    url = (database_url or "").strip() or None
    with _lock:
        if url == _configured_url:
            return
        if _engine is not None:
            _engine.dispose()
            _engine = None
            _SessionLocal = None

        _configured_url = url
        if not url:
            _use_database = False
            return

        eng = create_engine_for_url(url)
        init_schema(eng)
        _engine = eng
        _SessionLocal = make_session_factory(eng)
        _use_database = True


def reconfigure_for_tests(database_url: str | None) -> None:
    """Reset backend (tests only): dispose engine and apply a new URL or memory mode."""

    configure(None)
    with _lock:
        _memory.clear()
    configure(database_url)


def clear() -> None:
    """Remove all entries (tests and optional admin use)."""

    with _lock:
        _memory.clear()
        if _use_database and _SessionLocal is not None:
            with _SessionLocal() as session:
                session.execute(delete(QuestionLogRow))
                session.commit()


def list_sorted() -> list[LoggedQuestionEntry]:
    """Return all questions sorted by hour, then question number.

    Returns:
        List of entries in display order.
    """

    if not _use_database:
        with _lock:
            items = list(_memory.values())
        items.sort(key=lambda e: (e.hour, e.question_number))
        return items

    assert _SessionLocal is not None
    with _SessionLocal() as session:
        rows = session.execute(
            select(QuestionLogRow).order_by(QuestionLogRow.hour, QuestionLogRow.question_number)
        ).scalars().all()
    return [
        LoggedQuestionEntry(
            hour=r.hour,
            question_number=r.question_number,
            text=r.text,
            updated_at=r.updated_at,
        )
        for r in rows
    ]


def upsert(hour: int, question_number: int, text: str) -> tuple[bool, LoggedQuestionEntry]:
    """Insert or replace the question for (hour, question_number).

    Args:
        hour: Trivia hour (>= 1).
        question_number: Question index within that hour (>= 1).
        text: Question body.

    Returns:
        Tuple of (whether an existing row was replaced, the stored entry).
    """

    stripped = text.strip()
    now = (
        datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    )
    key = (hour, question_number)
    entry = LoggedQuestionEntry(
        hour=hour,
        question_number=question_number,
        text=stripped,
        updated_at=now,
    )

    if not _use_database:
        with _lock:
            overwritten = key in _memory
            _memory[key] = entry
        return overwritten, entry

    assert _SessionLocal is not None
    with _SessionLocal() as session:
        existing = session.execute(
            select(QuestionLogRow).where(
                QuestionLogRow.hour == hour,
                QuestionLogRow.question_number == question_number,
            )
        ).scalar_one_or_none()
        overwritten = existing is not None
        if existing:
            existing.text = stripped
            existing.updated_at = now
        else:
            session.add(
                QuestionLogRow(
                    hour=hour,
                    question_number=question_number,
                    text=stripped,
                    updated_at=now,
                )
            )
        session.commit()
        return overwritten, entry
