# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Thread-safe in-memory shared question log (hour + question number → text)."""
from __future__ import annotations

import threading
from dataclasses import dataclass
from datetime import datetime, timezone


@dataclass(frozen=True)
class LoggedQuestionEntry:
    """One stored question keyed by hour and question index."""

    hour: int
    question_number: int
    text: str
    updated_at: str


_lock = threading.Lock()
_entries: dict[tuple[int, int], LoggedQuestionEntry] = {}


def clear() -> None:
    """Remove all entries (intended for tests)."""

    with _lock:
        _entries.clear()


def list_sorted() -> list[LoggedQuestionEntry]:
    """Return all questions sorted by hour, then question number.

    Returns:
        List of entries in display order.
    """

    with _lock:
        items = list(_entries.values())
    items.sort(key=lambda e: (e.hour, e.question_number))
    return items


def upsert(hour: int, question_number: int, text: str) -> tuple[bool, LoggedQuestionEntry]:
    """Insert or replace the question for (hour, question_number).

    Args:
        hour: Trivia hour (>= 1).
        question_number: Question index within that hour (>= 1).
        text: Question body.

    Returns:
        Tuple of (whether an existing row was replaced, the stored entry).
    """

    stripped = text.strip()
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    key = (hour, question_number)
    entry = LoggedQuestionEntry(
        hour=hour,
        question_number=question_number,
        text=stripped,
        updated_at=now,
    )
    with _lock:
        overwritten = key in _entries
        _entries[key] = entry
    return overwritten, entry
