# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Run the FastAPI server (development-friendly defaults)."""
import logging
import sys

import uvicorn

from config import Config


def main() -> None:
    """Validate configuration and start Uvicorn with ``api:app``.

    Working directory should be ``trivia_application/backend`` so imports
    (``config``, ``core``, ``api``) resolve like ``python main.py``.

    Raises:
        SystemExit: If configuration validation fails.
    """
    try:
        Config.validate_for_api()
    except ValueError as exc:
        print(f"Configuration error: {exc}")
        sys.exit(1)

    logging.basicConfig(level=getattr(logging, Config.LOG_LEVEL, logging.INFO))
    Config.log_config()

    uvicorn.run(
        "api:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
    )


if __name__ == "__main__":
    main()
