# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Pydantic models for the HTTP API and SSE payloads."""
from urllib.parse import urlparse

from pydantic import BaseModel, Field, field_validator


class StartSessionRequest(BaseModel):
    """Client body for ``POST /api/start``."""

    twitch_url: str = Field(
        ...,
        min_length=1,
        description="Twitch channel or direct HTTP(S) audio stream URL (field name kept for compatibility)",
    )

    @field_validator("twitch_url")
    @classmethod
    def normalize_stream_url(cls, value: str) -> str:
        """Strip whitespace and validate an http(s) URL (Twitch or arbitrary stream).

        Args:
            value: Raw URL string from the client.

        Returns:
            str: Normalized URL string.

        Raises:
            ValueError: If the string is empty or missing a valid http(s) scheme.
        """
        stripped = value.strip()
        if not stripped:
            raise ValueError("twitch_url cannot be empty or whitespace only")
        parsed = urlparse(stripped)
        if parsed.scheme not in ("http", "https"):
            raise ValueError("URL must use http or https")
        if not parsed.netloc:
            raise ValueError("URL must include a host")
        return stripped


class StartSessionResponse(BaseModel):
    """Successful response after starting a session."""

    status: str = Field(description="Short status label, e.g. started")
    message: str = Field(description="Human-readable detail")


class StopSessionResponse(BaseModel):
    """Successful response after stopping a session."""

    status: str
    message: str


class HealthResponse(BaseModel):
    """Liveness payload for ``GET /health``."""

    status: str = "ok"


class TranscriptionEvent(BaseModel):
    """One SSE ``data:`` JSON payload for a transcription chunk."""


    text: str = Field(
        description=(
            "Transcribed text for this window, or the fixed placeholder "
            "``[no audio this chunk]`` when there was no usable audio or speech"
        ),
    )


class SessionConfigResponse(BaseModel):
    """Processing timing values exposed to the frontend for the progress bar."""

    audio_window_seconds: int = Field(description="Seconds of audio captured per Whisper window")
    segment_interval_seconds: int = Field(description="Seconds between each new transcription being triggered")


class LoggedQuestion(BaseModel):
    """One row in the shared question log."""

    hour: int = Field(ge=1, description="Trivia hour")
    question_number: int = Field(ge=1, description="Question number within that hour")
    text: str = Field(min_length=1, description="Question wording")
    updated_at: str = Field(description="When this row was last saved (ISO-8601 UTC)")


class QuestionLogListResponse(BaseModel):
    """Full list for GET /api/questions (sorted by hour, then question number)."""

    questions: list[LoggedQuestion]


class UpsertQuestionRequest(BaseModel):
    """Body for POST /api/questions."""

    hour: int = Field(ge=1, le=56, description="Trivia hour up to 56")
    question_number: int = Field(ge=1)
    text: str = Field(min_length=1)

    @field_validator("text")
    @classmethod
    def strip_non_empty_text(cls, value: str) -> str:
        """Reject empty or whitespace-only question text.

        Args:
            value: Raw ``text`` from the client.

        Returns:
            str: Stripped question text.

        Raises:
            ValueError: If nothing remains after stripping.
        """
        stripped = value.strip()
        if not stripped:
            raise ValueError("text cannot be empty or whitespace only")
        return stripped


class UpsertQuestionResponse(BaseModel):
    """Result of saving one question."""

    overwritten: bool = Field(description="True if this hour/Q# already had text")
    question: LoggedQuestion
