# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Pydantic models for the HTTP API and SSE payloads."""
from urllib.parse import urlparse

from pydantic import BaseModel, Field, field_validator


class StartSessionRequest(BaseModel):
    """Client body for ``POST /api/start``."""

    twitch_url: str = Field(..., min_length=1, description="Twitch channel URL")

    @field_validator("twitch_url")
    @classmethod
    def normalize_twitch_url(cls, value: str) -> str:
        """Strip whitespace and ensure the URL looks like a Twitch channel URL.

        Args:
            value: Raw URL string from the client.

        Returns:
            str: Normalized URL string.

        Raises:
            ValueError: If the string is empty, missing a valid scheme, or not Twitch.
        """
        stripped = value.strip()
        if not stripped:
            raise ValueError("twitch_url cannot be empty or whitespace only")
        parsed = urlparse(stripped)
        if parsed.scheme not in ("http", "https"):
            raise ValueError("URL must use http or https")
        host = (parsed.hostname or "").lower()
        if "twitch.tv" not in host:
            raise ValueError("URL must be a Twitch channel (hostname must include twitch.tv)")
        return stripped


class StartSessionResponse(BaseModel):
    """Successful response after starting a session."""

    status: str = Field(description="Short status label, e.g. started")
    message: str = Field(description="Human-readable detail")


class StopSessionResponse(BaseModel):
    """Successful response after stopping a session."""

    status: str
    message: str


class HealthResponse(BaseModel):
    """Liveness payload for ``GET /health``."""

    status: str = "ok"


class TranscriptionEvent(BaseModel):
    """One SSE ``data:`` JSON payload for a transcription chunk."""

    text: str = Field(description="Transcribed text for this window")
