# Code Generated by Sidekick is for learning and experimentation purposes only.
"""Fan-out transcription events to every SSE subscriber (each client gets its own queue)."""
from __future__ import annotations

import queue
import threading
from collections import deque
from typing import Any

from utils.logger import setup_logger

logger = setup_logger(__name__)


class TranscriptionFanout:
    """Broadcasts each transcription JSON payload to every subscriber queue.

    A bounded in-memory history allows new browsers to replay recent chunks when
    they join mid-session so everyone can align on the same live transcript.
    """

    def __init__(self, history_maxlen: int = 300) -> None:
        """Create an empty fan-out hub.

        Args:
            history_maxlen: Maximum transcription payloads to retain for replay.
        """
        self._lock = threading.Lock()
        self._history: deque[str] = deque(maxlen=history_maxlen)
        self._subscribers: list[queue.Queue[str | Any]] = []

    def publish(self, payload: str) -> None:
        """Append to replay history and push the same payload to every subscriber.

        Args:
            payload: JSON string (``TranscriptionEvent`` serialized).

        Raises:
            Nothing: full subscriber queues drop one event with a warning.
        """
        with self._lock:
            self._history.append(payload)
            subs = list(self._subscribers)
        for q in subs:
            try:
                q.put_nowait(payload)
            except queue.Full:
                logger.warning("Subscriber queue full; dropping one transcription event")

    def subscribe(self) -> tuple[queue.Queue[str | Any], list[str]]:
        """Register a new subscriber and return its queue plus a history snapshot.

        The snapshot should be sent over SSE before draining the queue so late
        joiners see the same recent transcript as existing clients.

        Returns:
            A ``(queue, snapshot)`` pair: live events arrive on ``queue`` after
            the snapshot has been replayed by the producer.
        """
        with self._lock:
            snapshot = list(self._history)
            q: queue.Queue[str | Any] = queue.Queue(maxsize=500)
            self._subscribers.append(q)
        return q, snapshot

    def unsubscribe(self, q: queue.Queue[str | Any]) -> None:
        """Remove a subscriber queue when its SSE connection ends.

        Args:
            q: The same queue object returned from ``subscribe``.
        """
        with self._lock:
            try:
                self._subscribers.remove(q)
            except ValueError:
                pass

    def publish_stop(self, sentinel: Any) -> None:
        """Notify every subscriber to end the SSE stream (e.g. session stopped).

        Args:
            sentinel: Distinct object placed on each queue (compared with ``is``).
        """
        with self._lock:
            subs = list(self._subscribers)
        for q in subs:
            try:
                q.put_nowait(sentinel)
            except queue.Full:
                logger.warning("Could not enqueue stop sentinel; subscriber queue full")
