# Code Generated by Sidekick is for learning and experimentation purposes only.
# tests/test_extraction.py
"""
Unit tests for question extraction
"""
import unittest
import os
from core.question_extractor import QuestionExtractor
from config import Config

class TestQuestionExtraction(unittest.TestCase):
    
    @classmethod
    def setUpClass(cls):
        """Initialize extractor once for all tests"""
        if not Config.OPENAI_API_KEY:
            raise unittest.SkipTest("OPENAI_API_KEY not configured")
        
        cls.extractor = QuestionExtractor(api_key=Config.OPENAI_API_KEY)
    
    def test_extract_simple_question(self):
        """Test extracting a simple question"""
        text = "Okay folks, this is question 3 of hour 2. What is the capital of France?"
        
        result = self.extractor.extract_question_info(text)
        
        self.assertEqual(result['question_number'], 3)
        self.assertEqual(result['hour_number'], 2)
        self.assertIn('capital', result['question_text'].lower())
        self.assertIn('france', result['question_text'].lower())
    
    def test_extract_no_question(self):
        """Test when no question is present"""
        text = "Welcome back everyone, the next song is going to be..."
        
        result = self.extractor.extract_question_info(text)
        
        self.assertIsNone(result['question_text'])
    
    def test_duplicate_detection(self):
        """Test duplicate question detection"""
        q1 = "What is the capital of France?"
        q2 = "What's the capital city of France?"
        recent = [q1]
        
        is_dup = self.extractor.is_duplicate(q2, recent)
        
        self.assertTrue(is_dup)

if __name__ == '__main__':
    unittest.main()
