# Code Generated by Sidekick is for learning and experimentation purposes only.
# tests/test_transcription.py
"""
Unit tests for transcription module
"""
import unittest
import numpy as np
from core.streaming_transcription import StreamingTranscriber
from config import Config

class TestTranscription(unittest.TestCase):
    
    @classmethod
    def setUpClass(cls):
        """Initialize transcriber once for all tests"""
        cls.transcriber = StreamingTranscriber(
            model_size="tiny",  # Use tiny for faster testing
            device="cpu"
        )
    
    def test_transcribe_silence(self):
        """Test transcribing silence"""
        # Generate 5 seconds of silence
        silence = np.zeros(5 * Config.SAMPLE_RATE, dtype=np.int16)
        
        result = self.transcriber.transcribe_audio_buffer(silence)
        
        # Should return empty or very short text
        self.assertTrue(len(result) < 10)
    
    def test_transcribe_short_audio(self):
        """Test transcribing very short audio"""
        # Generate 0.5 seconds of audio
        short_audio = np.random.randint(-1000, 1000, 
                                        Config.SAMPLE_RATE // 2, 
                                        dtype=np.int16)
        
        result = self.transcriber.transcribe_audio_buffer(short_audio)
        
        # Should handle without error
        self.assertIsInstance(result, str)

if __name__ == '__main__':
    unittest.main()
