# Code Generated by Sidekick is for learning and experimentation purposes only.
# tests/test_vod.py
"""
Test the application with a Twitch VOD (recorded stream)
This is useful for testing before going live
"""
import sys
import time
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from config import Config
from core import LiveTwitchAudioCapture, StreamingTranscriber
from utils import setup_logger

def test_with_vod(vod_url, duration_seconds=60):
    """
    Test transcription with a Twitch VOD
    
    Args:
        vod_url: URL to Twitch VOD (e.g., https://www.twitch.tv/videos/XXXXXX)
        duration_seconds: How long to test for
    """
    logger = setup_logger()
    logger.info(f"Testing with VOD: {vod_url}")
    
    # Initialize components
    capture = LiveTwitchAudioCapture(vod_url)
    transcriber = StreamingTranscriber(
        model_size=Config.WHISPER_MODEL_SIZE,
        device=Config.WHISPER_DEVICE
    )
    
    try:
        # Start capturing
        logger.info("Starting stream capture...")
        capture.start_stream()
        
        # Wait for stream to stabilize
        time.sleep(3)
        
        # Capture for specified duration
        logger.info(f"Capturing audio for {duration_seconds} seconds...")
        time.sleep(duration_seconds)
        
        # Get audio buffer
        logger.info("Getting audio buffer...")
        audio_buffer = capture.get_audio_buffer(30)
        
        if audio_buffer is None:
            logger.error("No audio captured!")
            return
        
        logger.info(f"Captured {len(audio_buffer)} samples")
        
        # Transcribe
        logger.info("Transcribing...")
        transcription = transcriber.transcribe_audio_buffer(audio_buffer)
        
        logger.info("=== TRANSCRIPTION ===")
        logger.info(transcription)
        logger.info("===================")
        
    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
    
    finally:
        capture.stop_stream()
        logger.info("Test complete")

if __name__ == "__main__":
    # Example: Use a past trivia stream VOD
    VOD_URL = "https://www.twitch.tv/videos/XXXXXXXX"  # Replace with actual VOD
    
    test_with_vod(VOD_URL, duration_seconds=60)
