# Code Generated by Sidekick is for learning and experimentation purposes only.
# utils/audio_utils.py
"""
Audio processing utility functions
"""
import wave
import numpy as np
from pathlib import Path
from config import Config

def save_audio_buffer(audio_buffer, filename, sample_rate=None):
    """
    Save numpy audio buffer to WAV file
    
    Args:
        audio_buffer: numpy array of int16 samples
        filename: output filename
        sample_rate: sample rate (Hz), defaults to Config.SAMPLE_RATE
    """
    if sample_rate is None:
        sample_rate = Config.SAMPLE_RATE
    
    filepath = Path(Config.TEMP_AUDIO_DIR) / filename
    
    with wave.open(str(filepath), 'wb') as wf:
        wf.setnchannels(Config.AUDIO_CHANNELS)
        wf.setsampwidth(2)  # 16-bit = 2 bytes
        wf.setframerate(sample_rate)
        wf.writeframes(audio_buffer.tobytes())
    
    return filepath

def load_audio_buffer(filename, sample_rate=None):
    """
    Load WAV file to numpy audio buffer
    
    Args:
        filename: input filename
        sample_rate: expected sample rate (Hz), defaults to Config.SAMPLE_RATE
    
    Returns:
        numpy array of int16 samples
    """
    if sample_rate is None:
        sample_rate = Config.SAMPLE_RATE
    
    filepath = Path(Config.TEMP_AUDIO_DIR) / filename
    
    with wave.open(str(filepath), 'rb') as wf:
        assert wf.getframerate() == sample_rate, "Sample rate mismatch"
        assert wf.getnchannels() == Config.AUDIO_CHANNELS, "Channel count mismatch"
        
        frames = wf.readframes(wf.getnframes())
        audio_buffer = np.frombuffer(frames, dtype=np.int16)
    
    return audio_buffer

def calculate_audio_duration(audio_buffer, sample_rate=None):
    """Calculate duration of audio buffer in seconds"""
    if sample_rate is None:
        sample_rate = Config.SAMPLE_RATE
    
    return len(audio_buffer) / sample_rate

def trim_silence(audio_buffer, threshold=500, sample_rate=None):
    """
    Trim silence from beginning and end of audio buffer
    
    Args:
        audio_buffer: numpy array of int16 samples
        threshold: amplitude threshold for silence detection
        sample_rate: sample rate (Hz)
    
    Returns:
        Trimmed audio buffer
    """
    if sample_rate is None:
        sample_rate = Config.SAMPLE_RATE
    
    # Find first non-silent sample
    start_idx = 0
    for i, sample in enumerate(audio_buffer):
        if abs(sample) > threshold:
            start_idx = i
            break
    
    # Find last non-silent sample
    end_idx = len(audio_buffer)
    for i in range(len(audio_buffer) - 1, -1, -1):
        if abs(audio_buffer[i]) > threshold:
            end_idx = i + 1
            break
    
    return audio_buffer[start_idx:end_idx]
