# Code Generated by Sidekick is for learning and experimentation purposes only.
# utils/logger.py
"""
Logging configuration for the application
"""
import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from config import Config
from colorama import init, Fore, Style

# Initialize colorama for cross-platform colored output
init(autoreset=True)

# Generate a shared session timestamp so both loggers use the same value
_SESSION_TIMESTAMP = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

class ColoredFormatter(logging.Formatter):
    """Custom formatter with colors for console output"""
    
    COLORS = {
        'DEBUG': Fore.CYAN,
        'INFO': Fore.GREEN,
        'WARNING': Fore.YELLOW,
        'ERROR': Fore.RED,
        'CRITICAL': Fore.RED + Style.BRIGHT
    }
    
    def format(self, record):
        # Add color to levelname
        levelname = record.levelname
        if levelname in self.COLORS:
            record.levelname = f"{self.COLORS[levelname]}{levelname}{Style.RESET_ALL}"
        return super().format(record)

def setup_transcription_logger():
    """Setup a dedicated logger for transcriptions.
    
    Writes to a session-timestamped file in the transcriptions log folder
    with a clean, readable format for end-user reference.
    """
    t_logger = logging.getLogger('Transcriptions')
    t_logger.setLevel(logging.INFO)
    
    # Avoid adding duplicate handlers on repeated calls
    if t_logger.handlers:
        return t_logger
    
    # Prevent propagation to root logger
    t_logger.propagate = False
    
    # Ensure directory exists
    os.makedirs(Config.TRANSCRIPTION_LOG_DIR, exist_ok=True)
    
    log_file = os.path.join(
        Config.TRANSCRIPTION_LOG_DIR,
        f'transcription_{_SESSION_TIMESTAMP}.log'
    )
    
    # File handler — clean format: timestamp + transcription text
    file_handler = logging.FileHandler(log_file)
    file_handler.setLevel(logging.INFO)
    file_formatter = logging.Formatter(
        '%(asctime)s\n%(message)s\n',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    file_handler.setFormatter(file_formatter)
    t_logger.addHandler(file_handler)
    
    return t_logger


def setup_logger(name='TriviaAssistant'):
    """Setup and return configured logger"""
    logger = logging.getLogger(name)
    logger.setLevel(getattr(logging, Config.LOG_LEVEL))
    
    # Clear any existing handlers
    logger.handlers.clear()
    
    # Console handler with colors
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setLevel(logging.INFO)
    console_formatter = ColoredFormatter(
        '%(levelname)s - %(message)s'
    )
    console_handler.setFormatter(console_formatter)
    
    # Ensure directory exists
    os.makedirs(Config.LOG_DIR, exist_ok=True)
    
    log_file = os.path.join(
        Config.LOG_DIR,
        f'app_{_SESSION_TIMESTAMP}.log'
    )
    
    # File handler
    file_handler = logging.FileHandler(log_file)
    file_handler.setLevel(logging.DEBUG)
    file_formatter = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    file_handler.setFormatter(file_formatter)
    
    # Add handlers
    logger.addHandler(console_handler)
    logger.addHandler(file_handler)
    
    return logger
