# Code Generated by Sidekick is for learning and experimentation purposes only.
# utils/text_utils.py
"""
Text processing utility functions
"""
import re
from Levenshtein import ratio

def normalize_text(text):
    """
    Normalize text for comparison
    - Lowercase
    - Remove extra whitespace
    - Remove punctuation
    """
    # Lowercase
    text = text.lower()
    
    # Remove punctuation except apostrophes
    text = re.sub(r"[^\w\s']", '', text)
    
    # Normalize whitespace
    text = ' '.join(text.split())
    
    return text

def calculate_similarity(text1, text2, method='jaccard'):
    """
    Calculate similarity between two text strings
    
    Args:
        text1: first text string
        text2: second text string
        method: 'jaccard', 'levenshtein', or 'word_overlap'
    
    Returns:
        Similarity score between 0 and 1
    """
    # Normalize texts
    text1 = normalize_text(text1)
    text2 = normalize_text(text2)
    
    if method == 'jaccard':
        return _jaccard_similarity(text1, text2)
    elif method == 'levenshtein':
        return ratio(text1, text2)
    elif method == 'word_overlap':
        return _word_overlap_similarity(text1, text2)
    else:
        raise ValueError(f"Unknown similarity method: {method}")

def _jaccard_similarity(text1, text2):
    """Calculate Jaccard similarity (word-level)"""
    words1 = set(text1.split())
    words2 = set(text2.split())
    
    intersection = len(words1 & words2)
    union = len(words1 | words2)
    
    if union == 0:
        return 0.0
    
    return intersection / union

def _word_overlap_similarity(text1, text2):
    """Calculate word overlap ratio"""
    words1 = set(text1.split())
    words2 = set(text2.split())
    
    if not words1 or not words2:
        return 0.0
    
    intersection = len(words1 & words2)
    
    # Average of overlap ratios
    overlap1 = intersection / len(words1)
    overlap2 = intersection / len(words2)
    
    return (overlap1 + overlap2) / 2

def extract_question_number(text):
    """Extract question number from text like 'question 5' or 'Q5'"""
    # Pattern: "question 5", "Q5", "Q. 5", "#5", etc.
    patterns = [
        r'question\s+(\d+)',
        r'q\.?\s*(\d+)',
        r'#\s*(\d+)',
        r'number\s+(\d+)'
    ]
    
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return int(match.group(1))
    
    return None

def extract_hour_number(text):
    """Extract hour number from text like 'hour 2' or 'round 2'"""
    patterns = [
        r'hour\s+(\d+)',
        r'round\s+(\d+)',
        r'session\s+(\d+)'
    ]
    
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return int(match.group(1))
    
    return None

def is_likely_question(text, min_length=50):
    """
    Heuristic check if text is likely a question
    
    Args:
        text: text to check
        min_length: minimum character length
    
    Returns:
        Boolean indicating if text looks like a question
    """
    if len(text) < min_length:
        return False
    
    # Check for question indicators
    question_indicators = [
        'what', 'when', 'where', 'who', 'why', 'how',
        'which', 'name', 'identify', 'in what year',
        'according to', 'true or false'
    ]
    
    text_lower = text.lower()
    
    # Must contain at least one indicator
    has_indicator = any(ind in text_lower for ind in question_indicators)
    
    # Check for question mark
    has_question_mark = '?' in text
    
    return has_indicator or has_question_mark
